// Code generated by "stringer -type=Version"; DO NOT EDIT.

package tlsdriver

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[VersionTLS10-769]
	_ = x[VersionTLS11-770]
	_ = x[VersionTLS12-771]
	_ = x[VersionTLS13-772]
	_ = x[VersionSSL30-768]
}

const _Version_name = "VersionSSL30VersionTLS10VersionTLS11VersionTLS12VersionTLS13"

var _Version_index = [...]uint8{0, 12, 24, 36, 48, 60}

func (i Version) String() string {
	i -= 768
	if i >= Version(len(_Version_index)-1) {
		return "Version(" + strconv.FormatInt(int64(i+768), 10) + ")"
	}
	return _Version_name[_Version_index[i]:_Version_index[i+1]]
}
